### ISSUE TITLE
test-whitspace successfully but with manual check

### ISSUE THREAD

**Issue by Cinux90** [while-true-do/ansible-skeleton#45]
### Type of Report

bug

### Actual behaviour

Run test-whitspace.sh, with is finished successfully but ask to check some lines manually. E.g.
```
[cinux@cinux while_true_do.repo_epel]$ /bin/bash tests/test-whitespace.sh 

**************************************** 
***       Whitespace Checking        *** 
**************************************** 

**************************************** 
***  Whitespace checking successful  *** 
**************************************** 
  
Please also check the below Markdown files manually: 
./README.md:52:- hosts: servers 
./README.md:64:We are really happy, when somebody is joining the hard work. Please have a look
```

### Expected behaviour

The test should be run in an error or a warning in case of manual checks. But never into successfully.
Also possible is an Output as following:
```
[cinux@cinux while_true_do.repo_epel]$ /bin/bash tests/test-whitespace.sh 

**************************************** 
***       Whitespace Checking        *** 
**************************************** 

**************************************** 
***  Whitespace checking complete  *** 
**************************************** 
Results:
Please also check the below Markdown files manually: 
./README.md:52:- hosts: servers 
./README.md:64:We are really happy, when somebody is joining the hard work. Please have a look
```

**Comment by daniel-wtd** [comment]
The script currently tries to check md files seperately and does not fetch the return from it properly.
@donvipre was this some design descision?

At least logically it seems fine, because the normal checks passed, but markdown output is forced to be manually checked.

**Comment by donvipre** [comment]
As markdown sometimes has "<br>" as trailing two spaces I decided to not fail the test..
Suggestions are welcome ;)

**Comment by daniel-wtd** [comment]
working in https://github.com/while-true-do/ansible-galaxy-skeleton/tree/rework-v1
