### ISSUE TITLE
Supported OS+Ansible Version

### ISSUE THREAD

**Issue by daniel-wtd** [while-true-do/ansible-skeleton#47]
### Type of Report

Enhancement

### Actual behaviour

- Supported OS is not visible in README.md
- Supported Ansible Version is not visible in README.md

### Expected behaviour

- Supported OS is clearly visible in README.md
- Supported Ansible Version is clearly visible in README.md
- Maybe other stuff from meta/main.yml could be included

### Attachments

Maybe we can use the pills/badges from here or so:
https://shields.io/#/

**Comment by Cinux90** [comment]
Sound like a good idea. :+1: 
But we should automate as much as possible. Otherwise we will work on fix and adjust meta information and have no time to fix bugs or implement new features.

**Comment by daniel-wtd** [comment]
Yep, I am currently thinking about this topic a lot. In total I am at the following approach:

- automated test-download from a test-repo
- build-script
  - Update meta-files
  - Update README
  - Run Tests locally
  - Check for some leftovers from skeleton or other "bad habit from tha past" :yum:

**Comment by daniel-wtd** [comment]
working in https://github.com/while-true-do/ansible-galaxy-skeleton/tree/rework-v1
