### ISSUE TITLE
discussion: Ansible 2.8 breaks builds

### ISSUE THREAD

**Issue by daniel-wtd** [while-true-do/ansible-skeleton#73]
Since Ansible 2.8 is currently incompatible with molecule and testinfra, I think we are having 2 options:

- disable testinfra checks during testing (verify)
- force to use ansible 2.7.10

both are working for me and can be done as a mass-pull-request. What do you think?

**Comment by Cinux90** [comment]
Tests are important and they should never be disabled because of an bug or something like that.
Im for forcing ansible 2.7.  quality > features

**Comment by daniel-wtd** [comment]
i will do so with the roles i am currently touching

**Comment by daniel-wtd** [comment]
workaround applied to all roles.
